query DATA($analysisId: String!) {
  sampleMatchedAnalysisPairs(analysisId: $analysisId) {
    normalSampleAnalysis {
      studyId
      analysisId
    }
    tumourSampleAnalysis {
      studyId
      analysisId
      completedRuns: inputForRuns(
        filter: { state: "COMPLETE", repository: "icgc-argo-workflows/sanger-wgs-variant-calling" }
      ) {
        runId
        publishedAnalyses: producedAnalyses(filter: { analysisState: PUBLISHED }) {
          analysisId
        }
      }
    }
  }
}
