query DATA($analysisId: String!) {
  analyses(filter: { analysisId: $analysisId }) {
    content {
      analysisId
      analysisState
      studyId
      completedRuns: inputForRuns(
        filter: {
          state: "COMPLETE"
          repository: "icgc-argo-workflows/open-access-variant-filtering"
        }
      ) {
        runId
        publishedAnalyses: producedAnalyses(filter: { analysisState: PUBLISHED }) {
          analysisId
          analysisType
        }
      }
    }
  }
}
