query DATA($analysisId: String!) {
  analyses(filter: { analysisId: $analysisId }) {
    content {
      analysisId
      analysisState
      studyId
      completedRuns: inputForRuns(
        filter: { state: "COMPLETE", repository: "dna-seq-processing-wfs" }
      ) {
        runId
        publishedAnalyses: producedAnalyses(filter: { analysisState: PUBLISHED }) {
          analysisId
          analysisType
        }
      }
    }
  }
}
